### ISSUE TITLE
PKGI freezes when searching for the word 'solider'

### ISSUE THREAD

**Issue by kenshin088** [mmozeiko/pkgi#12]
Not sure why this happens but when I search for 'solider' and press enter, the app freezes. It won't respond to any button presses. No choice but to manually close the app and restart it.

I think this happens anytime a game is not listed. I typed in "NFL game" just as a test and the same thing happened.

**Comment by mmozeiko** [comment]
I can confirm. If nothing is found then app freezes or crashes. I'll fix it.
I was testing only cases when it found something in results :)

**Comment by kenshin088** [comment]
Awesome! ya i was doing the same thing until I wanted to grab a game that wasnt there

**Comment by opoisso893** [comment]
Fix is working. 
No more crash while using "search" in right menu.
Thanks.
