### ISSUE TITLE
Can't select title if there is only 1 search result

### ISSUE THREAD

**Issue by dizz00** [mmozeiko/pkgi#24]
When using search function if the result is only 1, i can't select it. For example in my list there is only 1 version of dariusburst then i can't select it, but if i search tearaway that have 3 version i can select it normally.

**Comment by mmozeiko** [comment]
Can confirm - selection is at wrong position when there are too few results. I can still move it up (just keep repeating pressing of up button until selection is visible).

I'll fix this.

**Comment by MarioMasta64** [comment]
it also instantly error's out and exits the program if nothing exists with a matching title

**Comment by mmozeiko** [comment]
That is fixed in #12.
