### ISSUE TITLE
Want to see the size of the file

### ISSUE THREAD

**Issue by winui2526** [mmozeiko/pkgi#25]
I Want to see the size of the file

**Comment by mmozeiko** [comment]
You want to see size of which file? pkg files? Sizes of PKG files are specified in pkgi.txt file. If you leave them empty then they will not show up in GUI. You'll need to fix/update your pkgi.txt file if these are the sizes you are asking about.

**Comment by winui2526** [comment]
I Want to see Sizes of PKG files are specified in pkgi.txt file  
OK
thank

**Comment by MarioMasta64** [comment]
theres a clearly marked portion for inputting sizes into the file. im guessing your using that static link yea?

**Comment by mmozeiko** [comment]
If you want to see sizes from pkgi.txt file, you open it and see them in editor. I don't understand what is the issue with this.

**Comment by mmozeiko** [comment]
Closing issue, because no idea what needs to be done here. Please leave a comment with more detailed explanation.
