### ISSUE TITLE
game one channel

### ISSUE THREAD

**Issue by kanogunz0789** [mmozeiko/pkgi#26]
hey i need game one channel in pkgi to download plz can you add this aplication in pkgi

**Comment by mmozeiko** [comment]
What do you mean by "one channel"? What is channel?

**Comment by MarioMasta64** [comment]
they are asking you to add a game to a pkgi.txt you dont control because they dont understand how this works

**Comment by mmozeiko** [comment]
Oh, its a game name? I didn't realize that.

Yeah, this repository is about functionality of pkgi. Providing contents of pkgi.txt or config.txt is up to you.
