### ISSUE TITLE
[Idea] New design for PKGi (UI)

### ISSUE THREAD

**Issue by XF10C** [mmozeiko/pkgi#27]
It's me again. bring some new concepts PKGI.
 !!JUST FAN CONCEPT, NO MORE!!

![png](https://user-images.githubusercontent.com/30769120/32232881-a69674fc-be8b-11e7-8121-8f140c9e2e2c.png)
![pkgi2](https://user-images.githubusercontent.com/30769120/32232884-a96c569c-be8b-11e7-8615-8fb250a5ea3c.png)

**Comment by mmozeiko** [comment]
Too much wasted space. Those rectangles in first image should be smaller and laid out in 2d grid. But yeah, that's very close to something I want to implement.

Please continue discussion on UI in #1.
