### ISSUE TITLE
rename resume file

### ISSUE THREAD

**Issue by tomazzz369** [mmozeiko/pkgi#29]
you could rename resume file from titleid.resume (now) to contentid.resume because it can couse issue in the future when updates and dlcs will be supported, for example if i start download one dlc, i will cancel it and i start download second dlc with the same title id

edit:

or even better contentid_app.resume, contentid_update.resume, contentid_dlc.resume, because i forgot app and update have the same content id or something other unique like pkgfilename.resume

regards

**Comment by mmozeiko** [comment]
Please don't create issues with your "whishlist" about how code should look like and what it should do. DLCs are not implemented so there is zero reason to ask to change existing code to support something that does not exist.

If you want to discuss something about pkgi code, feel free to drop by discord or send me an email.

**Comment by MarioMasta64** [comment]
it might be a nice id tho, when it gets implemented *if* would you consider it? it sounds like a good idea to me. (only issue would be changing all the files for people in old releases which may be a pain)

**Comment by mmozeiko** [comment]
DLC resume will be handled correctly when it will be implemented. Discussing how resume files should be named is pointless at this point.
