### ISSUE TITLE
i made you an icon if you want.

### ISSUE THREAD

**Issue by MarioMasta64** [mmozeiko/pkgi#33]
![startup](https://user-images.githubusercontent.com/20806802/32412157-3480bc32-c1c5-11e7-89ad-fe0c169331ce.png)
heres a preview: 
![ps_messages_20171105_001519](https://user-images.githubusercontent.com/20806802/32412159-48d1e968-c1c5-11e7-987d-378aca3a687e.jpg)
feel free to close this if you dont like it.

**Comment by MarioMasta64** [comment]
if you think it looks off i could extend the P as well

**Comment by mmozeiko** [comment]
Can you make same change for icon0.png file?

**Comment by MarioMasta64** [comment]
the i is thinner on icon0.png i think? and causes it to look akward: 
![image](https://user-images.githubusercontent.com/20806802/33003592-99d26520-cd89-11e7-838b-29e0cfb98235.png)

**Comment by MarioMasta64** [comment]
or moreso their is more space vertically that makes it look off the first one only really works cause of the blue start button i suppose

**Comment by mmozeiko** [comment]
Looks fine. I'll use it. Thanks!
