### ISSUE TITLE
On screen controls don't reflect swapped O and X buttons in henkaku.

### ISSUE THREAD

**Issue by Quantum-cross** [mmozeiko/pkgi#36]

**Comment by mmozeiko** [comment]
I believe this is fixed in #6. Just not yet released.

**Comment by MarioMasta64** [comment]
they do for me :/ might be because im using 0.05-fix tho.

**Comment by fennectech** [comment]
It works but the controls at the bottom dont reflect the current settings when O is set to enter.  (the text at the bottom)
