### ISSUE TITLE
Support for titles that do not require zRIF

### ISSUE THREAD

**Issue by TheRadziu** [mmozeiko/pkgi#38]
Currently, there is no way to install pkg files that have no zRIF(and yet work without one just like Baseball Riot). I suggest allowing to install the titles that have "NO REQUIRED" set as zRIF (and ignore this value during install).

**Comment by fennectech** [comment]
why not simply use a dummy zrif?       would it check it and fail because of its presence?

**Comment by tomazzz369** [comment]
alll titles require license/zrif to installation, even pkg with license type free like Baseball Riot. in this case license is created by vitashell when you refresh live area

**Comment by mmozeiko** [comment]
What "NOT REQUIRED" means for work.bin? Its not required to be present? It needs to be full with zeroes? It needs to have correct header/contentid but key can be zero?

**Comment by TheRadziu** [comment]
that means it can be simply missing and game will install via vitashell with no issues.

**Comment by mmozeiko** [comment]
OK
