### ISSUE TITLE
Game won't install

### ISSUE THREAD

**Issue by CrippledGamerMax** [mmozeiko/pkgi#42]
Basically the game downloads then when it try to install it will say "ERROR installation Failed" 

Can anyone help?

**Comment by ghamson** [comment]
Check to see that the nonpdrm.skprx is loaded properly

**Comment by tomazzz369** [comment]
i get this error only if zrif is invalid. i tested over 100 games with pkgi, 0 issues with installation if zrif is valid

**Comment by huangjun-best** [comment]
Download the latest nonpdrm.skprx, copy it to ux0:tai and modify the ux0:tai/config.txt file to add the path to the module under *KERNEL as follows

**Comment by craig4242** [comment]
please may i have help id be grateful

**Comment by mmozeiko** [comment]
@craig4242 first get the NoNpDrm + VitaShell refresh working. If that will work, then pkgi will also work.

**Comment by craig4242** [comment]
Thankyou for help sorting my vita my pgki is working ace u guys are amazing !!

**Comment by craig4242** [comment]
Thankyou for help sorting my vita my pgki is working ace u guys are amazing !!
