### ISSUE TITLE
Create new vpk file after changes

### ISSUE THREAD

**Issue by jaffa-bw** [mmozeiko/pkgi#43]
The vpk file (0.05) is from 25th October and last change on source code is from 20th November.
Please create a new vpk file.
Note: i recognized at chapter 'Building', that you explained how to do it, but it's difficult for me.

Thanks in advance,
komser

**Comment by MarioMasta64** [comment]
i will compile it for you -shrug-

**Comment by MarioMasta64** [comment]
follow this: https://vitasdk.org/
then run:
cmake . && make

**Comment by mmozeiko** [comment]
I want to do a few more changes before creating next release. Currently I'm on vacation, I'll be back after new year.
