### ISSUE TITLE
Question: how to add background image in pkgi?

### ISSUE THREAD

**Issue by paulomatosx** [mmozeiko/pkgi#47]
![pkgi download unpack ps vita pkg files directly by mmozeiko](https://user-images.githubusercontent.com/33873743/35704483-d8f9d60c-0786-11e8-8d7a-12ae33a34495.jpg)

**Comment by mmozeiko** [comment]
You can change it in this file: https://github.com/mmozeiko/pkgi/blob/master/assets/background.png

**Comment by paulomatosx** [comment]
Thank you mmozeiko, I go to try build it.
I have vitasdk, libvita2d, but I am newbie with this.
