### ISSUE TITLE
Using Overclock or Amphetamine pkgi games

### ISSUE THREAD

**Issue by Cameron4Real** [mmozeiko/pkgi#50]
Is there a way to use Overclock or Amphetamine with pkgi games?

**Comment by RY0M43CH1Z3N** [comment]
I use Overclock with Resident Evil Revelation 2, downloaded from pkgi, so, yes, you can use it.

**Comment by Cameron4Real** [comment]
Thanks got it to work.
It didn't work when work with normal vita memory card but after i changed to SD2vita it's working. 
Also added *ALL to the config text.
