### ISSUE TITLE
Pkgi Crashes after loading Game Update list.

### ISSUE THREAD

**Issue by 123kennix** [mmozeiko/pkgi#53]
I tried on 2 different vitas and the update list crashes after completing 100% of the search. I'm unable to update games.

**Comment by mmozeiko** [comment]
That's probably because it doesn't find any results. Same issue as #12.

**Comment by 123kennix** [comment]
Well, actually, I was not searching, just loading the list. Games list is loading fine, DLC lists are okay too, but when I load the game Update list, crash ...

**Comment by mmozeiko** [comment]
What do you mean by DLC and update list?
pkgi does not support DLC and update PKG files. You update installed games from homescreen like usual - with yellow arrow icon.

**Comment by 123kennix** [comment]
Oh really?, that means that I can update a donwloaded game from PKGI on the homescreen?

**Comment by mmozeiko** [comment]
Yes, exactly. Once the game is installed with NoNpDrm (either with pkgi, or with VitaShell refresh) the game files are identical to "legit" downloaded game. That's why regular update from homescreen works.
