### ISSUE TITLE
Pkgi/Pkgj Errors, errors everywhere ...

### ISSUE THREAD

**Issue by LuKeAA666** [mmozeiko/pkgi#54]
I am literally losing it; however, I feel as if I have been missing on the configuration; I could use some help because I have no understanding of this configuration I need to do:

Just updated to 3.65 HENkaku Enso O; Using: An 8 GB PSVita Memory card AND A VitaAdapter with SD2Vita (which is read properly, all 170 GBs so I assume the configuration in that regard is ok? Can I even use them at the same time?) I'm using "Switch SD2Vita" and I'm set on ux0: for it; All the config are in my ur0:tai/ folder and are as follows: 
config.txt
 gamesd.skprx
 gamesd_uma0.skprx
 gamesd_ux0.skprx
 henkaku_config.bin
 nonpdrm.skprx (I updated it for 3.65)
 nonpsmdrm.skprx

 the config.txt file has the following lines:

iaddaiadda
*KERNEL ur0:tai/gamesd_ux0.skprx ur0:tai/nonpdrm.skprx ur0:tai/nonpsdrm.skprx

the tai folder under ux0:tai\ is pretty much empty (but it exists);

lastly, my pkgi folder is in: ux0:pkgi/; it contains a config.txt file which reads the following: **CENSORED**

Now to the issue:

I start PKGi, it won't show the list; the error says: "ERROR:pkgi.txt file missing or bad config.txt file?"

I tried switching from ux0 to uma0 on Switch SD2Vita; I get the list to show, but I get error when trying to install the Youtube app (ERROR Install Failed).

I try Pkgj v0.08; it shows the list, it downloads Youtube (to Pkgj FOLDER!) but it won't install it; if I switch out of the app, nothing was installed on the dashboard;

I don't know what to do anymore nor where to start; what am I missing? What am I doing wrong? I'd like to understand what I have to do to get the Pkgi/Pkgj to work properly and having one, clean, understandable setup for the various config.txt files; I can't seem to find guides to help with SD2Vita and no content on youtube.

Help's appreciated.

**Comment by mmozeiko** [comment]
That config file you specified is has wrong format for pkgi. If you want game url there, make sure it has one line in following format:

    url https://yoururl/

No url_ no url_updates, no url_dlcs. No idea what are those. Make sure it has newline at end. And it does not have utf8 BOM at beginning (use a good editor). Rest of options are not supported in pkgi.

And please don't post piracy URLS in issues.
