### ISSUE TITLE
May I request for download speed indicator

### ISSUE THREAD

**Issue by silverizer** [mmozeiko/pkgi#56]
Download speed indicator would really help out to tell if internet is slowing down
i hope you would consider this thanks

**Comment by lunalik2** [comment]
@silverizer Open an issue on [pkgj](https://github.com/blastrock/pkgj). Afaik, support for pkgi is completely dead.

**Comment by lunalik2** [comment]
@mmozeiko Sorry for posting a link to pkgj. I just assumed that support was dead, and pkgj was a fork anyways.

**Comment by mmozeiko** [comment]
Instead of complaining that project is dead, how about submitting pull requests and keeping it alive?
