### ISSUE TITLE
v0.44 DLC bug

### ISSUE THREAD

**Issue by Yoti** [mmozeiko/pkgi#63]
PKGj can't load more then 4096 items, probably memory issue.
![2019-01-04-033016](https://user-images.githubusercontent.com/1880088/50668662-7e1e3080-0fd1-11e9-90c3-642637da42cb.jpg)
![2019-01-04-033023](https://user-images.githubusercontent.com/1880088/50668663-80808a80-0fd1-11e9-97db-ffdca080ba65.jpg)

**Comment by mmozeiko** [comment]
Not relevant to pkgi.

**Comment by Yoti** [comment]
Sorry, wrong browser tab.
