### ISSUE TITLE
[Idea] New design for PKGi (LiveArea)

### ISSUE THREAD

**Issue by XF10C** [mmozeiko/pkgi#7]
My view on how PKGi might look in LiveArea

* Icon (Changed, now "original", maybe)
* Background
* StartUp icon (Changed, now "original", maybe)

![icon0](https://user-images.githubusercontent.com/30769120/32008090-8d90c760-b9d5-11e7-8252-62c70e4a4d6d.png)
![startup](https://user-images.githubusercontent.com/30769120/32008091-8dc29dbc-b9d5-11e7-9da6-50b810e598bc.png)
![bg](https://user-images.githubusercontent.com/30769120/31997586-b9a29c58-b9b6-11e7-9c5e-de30d5db9356.png)

**Comment by Byokugen** [comment]
Hey, what's wrong with my look?
Also, freeshop icon design? Nope I'm not letting you have that :-)

**Comment by chronoss09** [comment]
Background is good but icon is similar to freeshop for 3DS and Startup is for VitaShell.....

**Comment by Byokugen** [comment]
That's why my is good :-)

**Comment by mmozeiko** [comment]
I'm actually pretty happy with current icon.

But background looks nice, I'll check how it looks on device.

**Comment by chronoss09** [comment]
I want to create this without "DLC" and "Last modify" column
<a href="https://gyazo.com/ac3076fa8e4f3a475e3f03dcc493e314"><img src="https://i.gyazo.com/ac3076fa8e4f3a475e3f03dcc493e314.png" alt="https://gyazo.com/ac3076fa8e4f3a475e3f03dcc493e314" width="912"/></a>

**Comment by mmozeiko** [comment]
What do you mean by this screenshot? This is PC application. What background images have to do with it and its columns?

**Comment by chronoss09** [comment]
Yes, it's a PC application and it will be good to create something similar if possible
![gui nps browser](https://user-images.githubusercontent.com/17669980/32029920-6575533a-b9ef-11e7-8fc3-540962ae73d1.png)

**Comment by fennectech** [comment]
i would love this!

**Comment by fennectech** [comment]
I would love something like this    basicly perfect!!!!!

**Comment by fennectech** [comment]
Comment this on #1

**Comment by mmozeiko** [comment]
While this looks nice in screenshot, I'm pretty sure it won't be so nice on Vita, because its resolution is very small. Also navigation between items won't be pretty. I have a bit different plan - still have one big screen for navigating list of available items. And when you select item, it will pop up more detailed info + download (and maybe delete/run) buttons. And queue will be just tiny indicator at status bar + more detailed popup-list on select button. This is what I have documented in #1 / #2.

**Comment by fennectech** [comment]
would you make it possable to look through the list while the detailed information is up

**Comment by shaffervanity** [comment]
@chronoss09  Your dreams came true.
![nuevo diseno](https://user-images.githubusercontent.com/20178716/32237507-7d5a5612-be3b-11e7-8aee-976820ad9317.png)

**Comment by chronoss09** [comment]
Great job, very beautifull 👍

**Comment by MarioMasta64** [comment]
everyone is pasting this everywhere 🤔

**Comment by shaffervanity** [comment]
@MarioMasta64 Pasting what?

**Comment by MarioMasta64** [comment]
banner image. this is in like 2-3 different issues 🤔
